### ISSUE TITLE
Build mail/rspamd without LUAJIT option

### ISSUE THREAD

**Issue by mneumann** [DragonFlyBSD/DeltaPorts#1042]
By default, LUAJIT is used:

```
OPTIONS_DEFAULT_x86_64=         LUAJIT
```

But that leads to following problem when sending mail (the one I tried was 750 KiB in size):

```
PANIC: unprotected error in call to Lua API (not enough memory)
```

When I compile rpspamd w/o LUAJIT, it works!

**Comment by zrj-rimwis** [comment]
Option change pushed to DPorts/staged branch, thx for testing.
