### ISSUE TITLE
`py-borgbackup` broken

### ISSUE THREAD

**Issue by mneumann** [DragonFlyBSD/DeltaPorts#1212]
See FreeBSD bug report: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=265060

This has been fixed in FreeBSD ports. `devel/xxhash` and `archivers/py-borgbackup` need to be updated. Can we trigger an update for these two packages?

**Comment by tuxillo** [comment]
Seems it built in the last try: https://github.com/DragonFlyBSD/DeltaPorts/commit/1ca130007ffa2290a85d3e2dfd8a868b1a364cba

It should get in in the next package upload, but for now it's available in `dports/staged`
