### ISSUE TITLE
Fix lang/erlang and lang/erlang-runtime26

### ISSUE THREAD

**Issue by mneumann** [DragonFlyBSD/DeltaPorts#1478]
Attached is a dragonfly-specific patch required to properly make use of Elixir and it's package manager, both running on top of the Erlang VM. You'll otherwise you run into a cert error and basically can't use Elixir with erlang-runtime 26.

The patch will be part of Erlang/OPT 27.1 release. But as Erlang 26 will be around for a long time, it's wise to patch it.

The patch can be applied to both lang/erlang and lang/erlang-runtime26. I assume newer versions of Elixir require that functionality and fail for that reason (older versions work).

The patch (please drop the .txt suffix, it's there to make github happy):
[patch-lib_public__key_src_pubkey__os__cacerts.erl.txt](https://github.com/user-attachments/files/16752725/patch-lib_public__key_src_pubkey__os__cacerts.erl.txt)

**Comment by daftaupe** [comment]
@mneumann thanks for the patch, it should be in when we release the next batch of packages.
