### ISSUE TITLE
Submitted New Port for asterisk-chan_sccp to FreePBX ports collection

### ISSUE THREAD

**Issue by dkgroot** [DragonFlyBSD/DeltaPorts#157]
I submitted a new bug report to FreePBX with a port for a foreign asterisk channel driver called chan_sccp, last saturday. See: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=204346. Apparently the process of acceptance can take quite a while (based on the number of open bug reports for new ports). 

Would it be ok to create a new DeltaPort with the same information (not backed by FreePBX (yet)), or should i just be patient and wait for FreePBX to include the port first ? Just would like to know what you like better.

**Comment by jrmarino** [comment]
I prefer (greatly) that it gets through FreeBSD ports and trickles back

**Comment by dkgroot** [comment]
Ok supe, good to know. Will get back when it does :-)
