### ISSUE TITLE
Pulseaudio now a dependency of www/firefox, breaking sound support

### ISSUE THREAD

**Issue by ftigeot** [DragonFlyBSD/DeltaPorts#396]
I'm not sure if this is the right way to fix it but such a patch restores the old behavior of only having the ALSA option enabled by default:

```
--- Makefile.options.orig	2016-01-16 07:29:29.024278000 +0100
+++ Makefile.options	2016-01-15 06:18:26.491250000 +0100
@@ -5,7 +5,7 @@
 			OPTIMIZED_CFLAGS PGO PROFILE TEST
 
 OPTIONS_DEFAULT+=	DBUS FFMPEG GIO GSTREAMER LOGGING OPTIMIZED_CFLAGS \
-			${OPTIONS_MULTI_AUDIO} \
+			ALSA \
 			${MACHINE_CPU:tu:MSOFTFP:S/SOFTFP/INTEGER_SAMPLES/}
 
 OPTIONS_MULTI+=		AUDIO
```

**Comment by jrmarino** [comment]
1) it is absolutely the wrong way to do it
2) the current situation is "ALSA + PULSEAUDIO" not "PULSEAUDIO over ALSA"

So you are not re-enabling ALSA; it is already enabled.

**Comment by ftigeot** [comment]
1) I tried using Makefile.DragonFly but this didn't change anything; if there's a better way to remove PULSEAUDIO from the option values I'm all ears.

2) This the expected outcome: ALSA was used previously and it worked fine. Only did the addition of the PULSEAUDIO option value in recent FreeBSD ports changes did break sound for some users.

**Comment by jrmarino** [comment]
1) Removing PULSEAUDIO from MD is possible and not difficult.  Doing it depends on 2)

2) I'm not understanding.  ALSA was and still is built.  Why would adding pulseaudion IN ADDITION to ALSA break anything?  Both are active at the same time.

I certainly would NOT expect adding an option would break another option.  That is definitely not "an expected outcome" for me

**Comment by ftigeot** [comment]
2) I have no idea why but this is certainly the observed outcome.

1) I already tried to change Makefile.DragonFly and failed. I wouldn't have opened this issue if I had found the right code combination

**Comment by jrmarino** [comment]
well, there's no point to pulseaudio anyway because webrtc (it's main reason for existence) is hard disabled.  But to be clear, it's not at all expected that the presence of one option disrupts another.  They are supposed to be independent.

I'll fix the makefile.  Even if you knew the combination, you still would have add to open either an issue or a pull request to get the fix in.

**Comment by jrmarino** [comment]
done
https://github.com/DragonFlyBSD/DPorts/commit/9114d2c489ab095ab5cf07b771a4538f6f03d34d
