### ISSUE TITLE
net-mgmt/nagios-check_memcached_paranoid doesn't play nice

### ISSUE THREAD

**Issue by zrj-rimwis** [DragonFlyBSD/DeltaPorts#562]
problem:
NDIR=$(cd ${LOCALBASE}/net-mgmt/nagios-plugins && make)
that looks like a hack as in port origin break-out?
netutils.c uses replaced strerror (for whatever reason it sees the need)
but port doesn't link in replacement func code from nagios-plugins-2.1.1/gl/strerror.o
thus giving:
net-mgmt/nagios-plugins/nagios-plugins-2.1.1/plugins/netutils.o:netutils.c:function np_net_connect: error: undefined reference to 'rpl_strerror'

**Comment by jrmarino** [comment]
unrelated piggy back to catch attention: 
@zrj-rimwis : https://github.com/DragonFlyBSD/DPorts/issues/182
