### ISSUE TITLE
www/h2o does not startup on reboot

### ISSUE THREAD

**Issue by mneumann** [DragonFlyBSD/DeltaPorts#663]
FreeBSD supports ```${name}_env``` which we don't. The rc.d script for h2o has this line:

    h2o_env="H2O_PERL=${h2o_perl}"

and ```H2O_PERL``` is used in ```/usr/local/share/h2o/start_server```. The fallback is just ```perl```, which works well when logged in as ```root``` but not during rc startup.

There are two ways to fix it:

1. Adding a substitution to post-patch:
```
post-patch:
        ${REINPLACE_CMD} -e 's|exec $${H2O_PERL:-perl}|exec $${H2O_PERL:-${LOCALBASE}/bin/perl}|' \
                ${WRKSRC}/share/h2o/start_server
```

2. Support ```${name}_env``` in ```rc.subr```. Other ports will take advantage of.

**Comment by jrmarino** [comment]
option 2 sounds better.  Can you supply a patch to DF?

**Comment by mneumann** [comment]
@jrmarino https://github.com/mneumann/DragonFlyBSD/commit/63199a7e11804eb391bd92041d382cc0ff5d3834. Feel free to commit.

**Comment by mneumann** [comment]
Fixed with recent commit https://gitweb.dragonflybsd.org/dragonfly.git/commitdiff/a512831c9ad09a2356dbf9ee5d5d60ef84cbb985
