### ISSUE TITLE
www/chromium fails to build due to licensing framework updates

### ISSUE THREAD

**Issue by kworr** [DragonFlyBSD/DeltaPorts#812]
Synth ignores www/chromium:

    Purging any ignored/broken ports first ...
    00:00:07 www/chromium has been ignored: License BSD3CLAUSE LGPL21 MPL needs confirmation, but BATCH is defined
    00:00:07 Sanity check complete. Ports remaining to build: 0

**Comment by jrmarino** [comment]
fixed.  FreeBSD deleted the MPL license recently.
