### ISSUE TITLE
drm-next-kmod port  

### ISSUE THREAD

**Issue by nikolobok** [DragonFlyBSD/DeltaPorts#837]
Needs drm-next-kmod port

**Comment by mazocomp** [comment]
@nikolobok those are experimental modules for FreeBSD kernel which will be available in FreeBSD 11.2 and FreeBSD 12.0, if this port isn't added, I think it failed to build :)

**Comment by nikolobok** [comment]
I see many mentions about porting drm/kms to Dragonfly, but cannot find it in deltaports..
Could you explain how is it ported, is it in Dragonfly distr repo by default?

**Comment by mazocomp** [comment]
@nikolobok I forgot to add that FreeBSD also has DRM/KMS modules in base, drm-next-kmod port is experimental to add support to newer GPUs, so expect those changes to be merged in FreeBSD (12.0?) base system too:
https://github.com/freebsd/freebsd/tree/master/sys/dev/drm2
