### ISSUE TITLE
mail/dma is part of base :)

### ISSUE THREAD

**Issue by mazocomp** [DragonFlyBSD/DeltaPorts#861]

**Comment by jrmarino** [comment]
But it can be newer than the dma in base.

**Comment by mazocomp** [comment]
@jrmarino are you serious? You develop DMA and you (DragonFly BSD committers) don't keep it up-to-date in base? o_O

**Comment by tuxillo** [comment]
dma was written by @corecode, it's kept in one of his repos probably because other operating systems will be using it as well

**Comment by mazocomp** [comment]
@tuxillo that means changes are merged in base much later? Ok.

**Comment by corecode** [comment]
still taking patches!
