### ISSUE TITLE
x11-wm/i3-gaps Build

### ISSUE THREAD

**Issue by streaml1ne555** [DragonFlyBSD/DeltaPorts#902]
If the two patches from x11-wm/i3/dragonfly are brought into the i3-gaps folder this will build with no issue. I tested this last night on 5.4.1 with dports from a few days ago and manually bringing in the FreeBSD i3-gaps port from their svn.

**Comment by zrj-rimwis** [comment]
Thank you for bringing our attention to this. I'm i3 user and was not aware there is a fork.
Patches added in https://github.com/DragonFlyBSD/DeltaPorts/commit/5d474e873
The i3-gaps will be added to DPorts on next manual sync.
